# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options


before_script:
  - echo "Running Build"
   
after_script:
  - echo "After script section"

stages:
  - dependencycheck
  - test
  - Analyze
  - build
  - deploy
  - document

dependency:
  stage: dependencycheck
  script:
      - powershell.exe -file .\build\1.dependencies.ps1

Tests:
  stage: test
  script:
    - powershell.exe -file ".\build\pester.ps1"
  artifacts:
    reports:
      junit: "junitreport.xml"

Analyze:
  stage: Analyze
  script:
    - powershell.exe -file ".\build\4.Analyze.ps1"

build:
  stage: build
  script:
    - powershell.exe -file .\build\0.build.ps1
  artifacts:
    paths:
      - $($env:reponame)
  only:
    - master

Nuget:
  stage: deploy
  script:
    - powershell.exe -file .\build\3.deploy.ps1 -repotype $($env:repotype) -apikey $($env:apikey) -reponame $($env:reponame) -SourceLocation $($env:SourceLocation) -PublishLocation $($env:publishLocation)
  only:
    - master

.UpdateDocumentation:
  stage: document
  script:
    - powershell.exe -command "Update-MarkdownHelp -Path .\docs"
  only:
    - master